### PR TITLE
Fork binary instead of invoking shell

### PR DESCRIPTION
**Pull request by vkatsikaros**
This patch forks the browser binary, instead of calling `system` & setting it to the background. The incentive is https://github.com/gempesaw/Selenium-Remote-Driver/issues/280 As I haven't worked with portability before, I am unsure about `fork`, `open` (redirection), `kill` portability consequences.

Notes:
- used `exec LIST` with multiple elements in LIST, because if [there is only 1 element](http://perldoc.perl.org/functions/exec.html) (ie the string of the command to execute, arguments included in the string) 

>  If there is only one element in LIST, the argument is checked for shell metacharacters, and if there are any, the entire argument is passed to the system's command shell for parsing (this is /bin/sh -c on Unix platforms, but varies on other platforms). 

Unfortunately, this meant that I did changes in lots of places :(
- The binary now executes in the foreground (in the child process) and not in the background (see above)
- Double quotes, both for the program and the `--binary` argument, confused exec so I had to remove them. There is an SRD comment about paths that could contain spaces (totally makes sense), that is completely **ignored** in this patch.
- For windows, I didn't know where to apply the `2>&1` part for STDERR to STDOUT redirection (I am unsure if open's redirection is portable and has the same effect)
- I added the attribute `Selenium::Firefox::signal_shutdown_binary` to demo the change, there might be a better way to do it (and avoid the extra attribute)?
- I had to do a Moo workaround (I am a Moo-noob :) ) to assign arrayref to an attribute, and I converted `builder` to `default`. There might be a more elegant solution to this, and I am not sure if this has any side effects.

I tested this with geckodriver 0.10 and firefox 49 and it works ok. geckodriver is launched, no STDERR/STDOUT from the child is printed (so the redirection seems to be working), and after some webdriver commands `shutdown_binary` does signal the child. When the main program exits, there is neither firefox or geckodriver running.

Happy to do more coding and/or tests if needed. Happy to code alternatives if the change looks too pervasive (but I'll might some directions).

### CODE REVIEW

**Comment by gempesaw** [comment]
> Unfortunately, this meant that I did changes in lots of places :(

Ah, yeah ... I can see why, nbd.

> - The binary now executes in the foreground (in the child process) and not in the background (see above)

👍 

> Double quotes, both for the program and the --binary argument, confused exec so I had to remove them. There is an SRD comment about paths that could contain spaces (totally makes sense), that is completely ignored in this patch.

Yeah, I mostly found this for Windows `Program Files` path. Blergh, windows is a pain :p 

> For windows, I didn't know where to apply the 2>&1 part for STDERR to STDOUT redirection (I am unsure if open's redirection is portable and has the same effect)

uh, no idea either.

> I added the attribute Selenium::Firefox::signal_shutdown_binary to demo the change, there might be a better way to do it (and avoid the extra attribute)?

seems fine. could maybe also do `! $self->_is_old_ff` ... but I like not tying the kill behavior to a particular browser, in case we need to do it to the others. oh hmmm but perhaps it should be in CanStartBinary, with default of 0 and then Selenium::Firefox turns it on and the others like ::Chrome don't have the attr in them so it never even gets called or initialized.

> I had to do a Moo workaround (I am a Moo-noob :) ) to assign arrayref to an attribute, and I converted builder to default. There might be a more elegant solution to this, and I am not sure if this has any side effects.

Oh? I didn't know this was an issue. AFAIK, `builder` and `default` (when passing both an anonymous subroutine) do pretty much the same thing (which is to execute the anon sub to figure out the value for the Moo-attribute). `builder` does also take a string like `_the_name_of_a_builder_function` and executes the function with that name, whereas `default` would take that string and store it directly, but the cases here are anon subs and not strings, so ... I don't know that there's any difference between them for us, and so probably (hopefully) not any unwanted side effects. c:

Uh, I'll have to try it out on Windows at some point. google seems wary about [windows and fork](https://www.google.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=windows%20perl%20fork&oq=windows%20perl%20fork&aqs=chrome..69i57j0l5.1248j0j7) so uhh we'll see, I guess! 

Thanks c:

**Comment by vkatsikaros** [comment]
Nice, let me know if I can be of more assistance.

> > I had to do a Moo workaround (I am a Moo-noob :) ) to assign arrayref to an attribute, and I converted builder to default. There might be a more elegant solution to this, and I am not sure if this has any side effects.

> Oh? I didn't know this was an issue. AFAIK, builder and default (when passing both an anonymous subroutine) do pretty much the same thing (which is to execute the anon sub to figure out the value for the Moo-attribute). builder does also take a string like _the_name_of_a_builder_function and executes the function with that name, whereas default would take that string and store it directly, but the cases here are anon subs and not strings, so ... I don't know that there's any difference between them for us, and so probably (hopefully) not any unwanted side effects. c:

This was actually the most time consuming part; making  [`_binary_args` builder](https://github.com/gempesaw/Selenium-Remote-Driver/pull/289/commits/3971df6726782c1f3668b9e2616a9e5f1e29c2c8#diff-46296c5f145ae8a2b9157d7eafe3b602L146) populate the attribute with a list or arrayref. Otherwise I always got 1 element, the last element of the list or arrayref :P PS I am Moo-noob so I might have missed sth completely obvious

**Comment by vkatsikaros** [comment]
Hm, I think that something isn't quite right in my patch. When the main thread that calls the `Selenium::Firefox` dies, everything seems to be ok in the end. But it seems that while the main thread is alive, the geckdriver processes actually don't get killed. I'll dig more into that.

Example
--------
```
#!/usr/bin/perl
use strict;
use warnings;
use feature qw(say);
use Selenium::Firefox;

my $driver = Selenium::Firefox->new();
$driver->get( 'http://www.adzuna.co.uk/' );
$driver->shutdown_binary();
say 'all fine';
say 'now lets sleep for a bit';
sleep(60);
say 'done';
```
Added a poor man's debugging in the kill's for loop:
```
$ git diff
diff --git a/lib/Selenium/CanStartBinary.pm b/lib/Selenium/CanStartBinary.pm
index 0118d70..334019a 100644
--- a/lib/Selenium/CanStartBinary.pm
+++ b/lib/Selenium/CanStartBinary.pm
@@ -376,6 +376,7 @@ sub shutdown_binary {
 
     if($self->has_signal_shutdown_binary && $self->signal_shutdown_binary) {
         for my $sig (15, 2, 9) {
+print "kill $sig " . $self->binary_pid . "\n";
             kill($sig, $self->binary_pid) or last;
             sleep 1;
         }

```

The output is:
```
kill 15 4435
kill 2 4435
kill 9 4435
all fine
now lets sleep for a bit
done
kill 15 4435
kill 2 4435
kill 9 4435

```
Notes
--------
1. The kill (ie the shutdown_binary) seems to be called twice, which doesn't look ok.
2. All 3 signals are signaled to the geckodriver process. I might be doing sth wrong...
3. During the sleep, ie after shutdown_binary, but before the main thread terminates, the geckodriver process is still there (possible due to the above)
```
$ pstree -p 4434
perl(4434)───geckodriver(4435)
```

**Comment by vkatsikaros** [comment]
Regarding the leftover geckodriver process after singalling it, I'd say it's a geckodriver problem? Unless I am doing something stupid, I can replicate the behavior without Selenium-Remote-Driver, see https://github.com/mozilla/geckodriver/issues/317

**Comment by troglodyne** [comment]
Looked at the code in this PR. Some notes:

If you are trying to fork + exec and only kill the process later, then you need to be doing a 'non-blocking' waitpid() in a SIGCHLD handler (or later, like when you were doing the kill operation in the PR).
See http://perldoc.perl.org/functions/waitpid.html for a 'non-blocking' example.

Certainly the non-blocking variety would be more likely to kill your zombies, as the entire reason zombification happens is because the parent did not respond to SIGCHLD. When this occurs, the only cure to zombification is the parent process exiting, as then the init system inherits the (now orphaned) zombies and reaps them (which is what you are currently seeing).

As such, using 'kill' to try to remove zombies will be pointless, as they are already dead. Only
a) killing the parent
or
b) doing waitpid to accept the SIGCHLD response from the child process then reap it
will do that.

The 'Perl Cookbook' also has a more in-depth example of using non-blocking waitpid and a SIGCHLD handler:
https://docstore.mik.ua/orelly/perl/cookbook/ch16_20.htm

**Comment by teodesian** [comment]
"For windows, I didn't know where to apply the 2>&1 part for STDERR to STDOUT redirection (I am unsure if open's redirection is portable and has the same effect)"

I think that Capture::Tiny is portable.

**Comment by vkatsikaros** [comment]
@troglodyne, @teodesian thanks for the comments. I think I get this now - a few additional months dealing with similar issues helped too :) If this is still interesting for SRD (certainly is for me here and the timing is perfect), I can rebase/resolve conflicts and suggest a patch.

**Comment by teodesian** [comment]
@vkatsikaros Sounds great -- I need to get up to speed on the geckodriver bits of the module anyways, given I'm the maintainer now.  Bring on the rebased patches :D

**Comment by teodesian** [comment]
Unfortunately this won't work due to the nature of the driver binaries.  They daemonize, orphaning themselves from the process group.  As such, we gotta resort to dirty tricks like in shutdown_windows_binary.

**Pull request closed without merging**
