### PR TITLE
Update CanStartBinary.pm

### PR DESCRIPTION
**Pull request by fayland**
do not print on STDOUT since it can be used in web

### CODE REVIEW

**Comment by teodesian** [comment]
Why not change the print to a warn?

Would we want to suppress that output to error_log for the event we are running in a web template?

Should that be controlled by a verbosity flag?  Sounds like a good feature request to me.

**Comment by fayland** [comment]
Hello. warn works good for me as well. :) you can reject the PR and do a change. Thanks

**Comment by teodesian** [comment]
Sounds good -- I'll make an issue to track this

**Comment by teodesian** [comment]
Added as #423

**Pull request closed without merging**
