### PR TITLE
Added W3C WebDriver support when using Chrome

### PR DESCRIPTION
**Pull request by mpspahr**
Added W3C WebDriver support for Chrome which provides the ability to use Chrome and chromedriver v75+ in default w3c mode.

https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

### CODE REVIEW

**Comment by teodesian** [comment]
Thanks Matt, will fix up tests and release today

**Comment by aaannz** [comment]
Is it correct to assume that it is now required to use chrome 75 and newer or `$driver->{is_wd3} = 0;` must be explicitly set with Chrome 74 and older?

**Comment by teodesian** [comment]
Indeed.  This likely needs to be reflected in the documentation.

I will update this sometime tomorrow (back from holidays in US).

**Comment by teodesian** [comment]
4db6816

**Pull request merged**
